
























































plt.show()lidar_vis.enable_slider_and_buttons(fig)lidar_vis.add_subplot(axs)# Use axs[0] for the first subplot (since axs is a 1D array)fig, axs = plt.subplots(1, 1, figsize=(20, 20), subplot_kw={'projection': 'polar'})lidar_vis = AlgorithmViewer(logfile_path)    constants.reload_constants()    )        "No config.json file was found in the log directory. Loading current configuration."        "No Backup Config Found",    messagebox.showinfo(else:        constants.reload_constants()        # Reload constants from the current config file    else:        constants.reload_constants(config_backup_path)        # Reload constants from the backup config file    if use_backup:    )        "A config.json file was found in the log directory.\nDo you want to load this backed up configuration?\nClick 'Yes' for backup constants or 'No' for current config."        "Load Configuration",    use_backup = messagebox.askyesno(    # Ask the user which configuration to loadif os.path.exists(config_backup_path):# Check if a config.json file exists in the log directoryconfig_backup_path = os.path.join(log_directory, "config.json")log_directory = os.path.dirname(logfile_path)# Determine the directory of the log file    exit(0)    print("No log file selected. Exiting.")if not logfile_path:)    filetypes=(("log files", "*.log"), ("all files", "*.*"))    title="Select Log File",    initialdir=logs_dir,logfile_path = filedialog.askopenfilename(root.withdraw()root = tk.Tk()logs_dir = os.path.join(os.path.dirname(__file__), "../logs/", today)today = datetime.date.today().strftime("%Y-%m-%d")from alogorithm_plot import AlgorithmViewerimport matplotlib.pyplot as pltimport constantsimport datetimefrom tkinter import filedialog, messageboximport tkinter as tkimport os